### ISSUE TITLE
[BUG] i cant upload new map , a

### ISSUE THREAD

**Issue by fisher762** [AdamKyle/flare#41]
hello
i have some problems 
1- when i try to add new map i got this
![image](https://user-images.githubusercontent.com/410750/198827121-898e280c-e3e9-4bdf-beee-ec35a9fcb43b.png)

2- where i can import kingdoms ? i cant find it in admin panel 

3-i cant import npcs 
![image](https://user-images.githubusercontent.com/410750/198827226-5a06d724-5675-4ad7-94a2-a27845a0b165.png)

**Comment by fisher762** [comment]
game at localhost
http://localhost/flare/public/

**Comment by fisher762** [comment]
also when create new account and login i got this
![image](https://user-images.githubusercontent.com/410750/198827367-c28a405b-aa26-48f8-9fb0-154d1a9ca4c5.png)

**Comment by fisher762** [comment]
Firefox can’t establish a connection to the server at ws://localhost:6001/app/?protocol=7&client=js&version=5.1.1&flash=false. [vendor.js:6046:15](http://localhost/js/vendor.js?id=7d0d76640167bd6c8514a90ad71877ac%20line%203069%20%3E%20eval)
The connection to ws://localhost:6001/app/?protocol=7&client=js&version=5.1.1&flash=false was interrupted while the page was loading. [vendor.js:6046:15](http://localhost/js/vendor.js?id=7d0d76640167bd6c8514a90ad71877ac%20line%203069%20%3E%20eval)
Firefox can’t establish a connection to the server at wss://localhost/app/?protocol=7&client=js&version=5.1.1&flash=false. [vendor.js:6046:15](http://localhost/js/vendor.js?id=7d0d76640167bd6c8514a90ad71877ac%20line%203069%20%3E%20eval)
The connection to wss://localhost/app/?protocol=7&client=js&version=5.1.1&flash=false was interrupted while the page was loading.
